### ISSUE TITLE
describeRoute breaks RPC type inference for GET methods

### ISSUE THREAD

**Issue by teovillanueva** [rhinobase/hono-openapi#10]
Hello, as the title says, when using describeRoute on a GET method, the RPC client types stop working.

<img width="526" alt="image" src="https://github.com/user-attachments/assets/10583075-6603-4bb6-9cae-1e1d518b1268">

<img width="329" alt="image" src="https://github.com/user-attachments/assets/72f0732b-c724-4dd6-a15a-ddce021fb4da">

If I remove the describeRoute `meData` gets typed correctly.

**Comment by teovillanueva** [comment]
NOTE: This happens only with GET. Other methods work correctly :)

**Comment by MathurAditya724** [comment]
Is this still happening in the new release?

**Comment by thecuvii** [comment]
Encounter a similar problem for GET route without any params, eg:

```ts
new Hono().get('/user/info', 
  describeRoute({...}), 
  // RPC return type will be never if remove this empty object validator
  zValidator('param', z.object({})),
  (c) => c.json({ age: 1 }, 200))
```

**Comment by MathurAditya724** [comment]
I have created a basic reproduction for this - https://stackblitz.com/edit/stackblitz-starters-ldpp3nju?file=index.ts, it doesn't seem to be an issue. Can you confirm if this is correct?

**Comment by thecuvii** [comment]
Yes, I can't reproduce it now with the latest versions of Hono, Hono OpenAPI, and TypeScript.
