### ISSUE TITLE
Using path param validation creates duplicates in the openapi json

### ISSUE THREAD

**Issue by iuwqyir** [rhinobase/hono-openapi#17]
When I create an endpoint that validates path params

```nodejs
import { validator } from "hono-openapi/zod";

const todos = new Hono();

todos.get(
  "/:id",
  describeRoute({
    description: "Get a single todo",
  }),
  validator("param", z.object({ id: z.string().uuid() })),
  async (c) => {
    const id = c.req.valid("param").id;
  }
)
```

Then the openapi JSON generated includes 2 objects for `id`. One in path and the other in param.
```
...
"parameters": [
          {
            "schema": {
              "type": "string"
            },
            "in": "path",
            "name": "id",
            "required": true
          },
          {
            "in": "param",
            "name": "id",
            "schema": {
              "type": "string",
              "format": "uuid"
            },
            "required": true
          }
        ]
...
```

Which then breaks the scalar UI and I am unable to try any requests due to this error
```
{
  "_errors": [],
  "parameters": {
    "1": {
      "_errors": [],
      "in": {
        "_errors": [
          "Invalid enum value. Expected 'path' | 'query' | 'header' | 'cookie', received 'param'"
        ]
      }
    },
    "_errors": []
  }
}
```

**Comment by adamdottv** [comment]
Also just ran into this. Were you planning to contribute?

**Comment by iuwqyir** [comment]
> Also just ran into this. Were you planning to contribute?

I don't know when I would get to this

**Comment by adamdottv** [comment]
> > Also just ran into this. Were you planning to contribute?
> 
> 
> 
> I don't know when I would get to this

Cool, I might take a stab at it

**Comment by MathurAditya724** [comment]
Interesting, so the expected output should only include the path entry for id, without the additional param entry, correct?

**Comment by adamdottv** [comment]
> Interesting, so the expected output should only include the path entry for id, without the additional param entry, correct?

Only question I would have is whether we can manipulate the metadata (description, example, etc.) for the path definitions? I know I can with parameter, but obviously we can't duplicate the path and parameter for the same field.

**Comment by MathurAditya724** [comment]
You can add metadata properties in Zod by extending it and using `.openapi` described in the `README.md`. For this issue, I am thinking of replacing the _path_ definitions with _params_ (if they exist and _name_ is the same) so that we can have the metadata for the defined props as well as keep the ones without it.
