### ISSUE TITLE
Arktype validation not working

### ISSUE THREAD

**Issue by ThatTonybo** [rhinobase/hono-openapi#23]
I am trying to set up OpenAPI on my routes. I've gotten it working but it's not showing request bodies. I assumed I had to use the provided validator instead of my own hono validator.

However I now get this error:
```ts
import { validator as aValidator } from 'hono-openapi/arktype';

app.post('/', describeRoute({ ... }), aValidator('json', schema), (c) => { ... });
```

Returns the following error:
```
Property 'innerToJsonSchema' is protected but type 'ProtoNode' is not a class derived from 'ProtoNode'.ts(2345)
```

**Comment by MathurAditya724** [comment]
We have this basic example working - https://github.com/rhinobase/hono-openapi/blob/main/apps/sandbox/src/routes/arktype.ts, you can use it as a reference.

If the issue persists, can you share a reproduction?

**Comment by ThatTonybo** [comment]
Tried implementing what the example has and running into the same issue:
![image](https://github.com/user-attachments/assets/49d8350d-74c4-435b-aa9b-6bc7e62f7bdd)
Happens with any of my Arktype types I provide it

**Comment by marcomuser** [comment]
@ThatTonybo could you share how you serve your project (node, tsx etc.) and what module and moduleResolution settings you are using in your tsconfig?

**Comment by marcomuser** [comment]
> We have this basic example working - https://github.com/rhinobase/hono-openapi/blob/main/apps/sandbox/src/routes/arktype.ts, you can use it as a reference.
> 
> If the issue persists, can you share a reproduction?

This example is using moduleResolution bundler in a commonjs project, while serving via tsx. Tsx makes the whole thing work as it handles all differences between cjs and esm. I suspect that without tsx it would stop working because arktype is a esm only library.

**Comment by ThatTonybo** [comment]
> @ThatTonybo could you share how you serve your project (node, tsx etc.) and what module and moduleResolution settings you are using in your tsconfig?

Project is being served with Bun, so I assume kinda similar to tsx, not too sure. 

Tsconfig is set to module ESNext and moduleResolution bundler

**Comment by marcomuser** [comment]
Ok than I suppose it's a separate issue. 👍 Bun should work similarly to tsx as you said.

**Comment by NamesMT** [comment]
@MathurAditya724 The problem seems to be caused if the user installs the latest arktype version (rc 26), if using rc 25 like the same as in this repo, there is no error.

**Comment by ThatTonybo** [comment]
Interestingly, different error if I update arktype to rc 28:
![image](https://github.com/user-attachments/assets/8b27d7af-a3b1-48e1-b3ec-6d823b4f7dec)
Using rc 25 as mentioned seems to have no errors
