### ISSUE TITLE
Route with parameter such as `/:id` breaks

### ISSUE THREAD

**Issue by bdazzledev** [rhinobase/hono-openapi#27]
![image](https://github.com/user-attachments/assets/edeff69e-8625-49cb-a0c5-1d4deef6eebf)

A route with any route parameter in breaks the Swagger doc generation with the following error:

![image](https://github.com/user-attachments/assets/54d93f07-0d66-4e4a-a4de-b1996ed938f0)

**Comment by bdazzledev** [comment]
Apologies variation of this already discussed here https://github.com/rhinobase/hono-openapi/issues/25#issuecomment-2556774686

**Comment by Curetix** [comment]
I think some changes in v0.3.0 (#19) broke this, downgrading back to v0.2.1 resolved the issue for me.

**Comment by psi-4ward** [comment]
Yes, pushing an object to the array fixes the issue:

```ts
            if (index !== -1) schema.parameters[index].in = "path";
            else schema.parameters.push({
                schema: { type: "string" },
                in: "path",
                name: param,
                required: true,
              });
```
