### ISSUE TITLE
openAPISpecs Does Not Accept app When Env Type is Passed

### ISSUE THREAD

**Issue by luisbytes** [rhinobase/hono-openapi#6]
Hi @MathurAditya724 When using hono-openapi with a Hono app typed with Env, the openAPISpecs function does not accept app as an argument, resulting in an error or unexpected behavior. The Env type includes specific bindings, which may be causing this issue.

```typescript
type Env = {
  Bindings: {
    MY_VAR: string;
  };
};

const app = new Hono<Env>;

app.get(
  "/openapi",
  openAPISpecs(app, {
    documentation: {
      info: {
        title: "Hono",
        version: "1.0.0",
        description: "API for greeting users",
      }
    },
  })
);
```

Error: `Argument of type 'Hono<Env, BlankSchema, "/">' is not assignable to parameter of type 'Hono<BlankEnv, BlankSchema, "/">'`

**Comment by MathurAditya724** [comment]
Hey 👋🏼, thanks for pointing it out. This will be resolved in the next version release.
